### ISSUE TITLE
Breadcrumbs wrong on various pages

### ISSUE THREAD

**Issue by nicolaspayette** [drozas/cecan#40]
On this page:
http://www.cecan.ac.uk/who-are-we/collaborating-partners

The breadcrumbs at the top show:

> Home > Who are we? > Other Partners >

It should probably be:

> Home > Who are we? > Co-investigators >

@drozas, let me know if you would have preferred that I report this through some other channel.

**Comment by nicolaspayette** [comment]
Actually, the breadcrumbs are wrong on some other places too. For example, on the various "people" pages (e.g. http://www.cecan.ac.uk/who-are-we/people/petra-ahrweiler), they're always:

> ```
>  Home > Who are we? > CECAN team > Michelle Boath > 
> ```

instead of being the person you're viewing.

**Comment by drozas** [comment]
Thanks @nicolaspayette ! Actually, using issues at github is great! :-) I will take a look at this when I find some time ;-)

**Comment by drozas** [comment]
Quick look: working while logging as root. Seems to be a problem with the cache system of that module. TO-CHECK

**Comment by drozas** [comment]
TO-CHECK : http://www.gregboggs.com/drupal8-breadcrumbs/

**Comment by drozas** [comment]
Check if due to https://www.drupal.org/project/menu_trail_by_path

**Comment by drozas** [comment]
Seems related -https://www.drupal.org/node/2723061

**Comment by drozas** [comment]
Possible solution - https://www.drupal.org/project/current_page_crumb

**Comment by drozas** [comment]
Also https://www.drupal.org/project/easy_breadcrumb

**Comment by drozas** [comment]
See https://www.drupal.org/node/2723061 (rel. to core)

**Comment by drozas** [comment]
Carry out #44 when patch for this is officially included.

**Comment by drozas** [comment]
Check locally with first 8.2.x version - https://www.drupal.org/project/drupal/releases/8.2.0

**Comment by drozas** [comment]
Trying easybreadcrumbs locally

**Comment by drozas** [comment]
Works! Requires disable  Include the current page as a segment in the breadcrumb . Extra >

**Comment by drozas** [comment]
Also enabling Use the real page's title when available

**Comment by drozas** [comment]
Checking report - http://cecan.ac.uk/admin/reports/status OK

**Comment by drozas** [comment]
Updating database *- http://www.cecan.ac.uk/update.php

**Comment by drozas** [comment]
Deploying and testing in prod

**Comment by drozas** [comment]
Successfully deployed and tested.
